[pytest]
env = 
    SOLR_ADDRESS=http://localhost:8999
    SOLR_MLT_PROCESS_CORE=test_dag_mlt_process
    FAISS_ADDRESS=http://localhost:8083

addopts = 
    -v
    -s 
    --cov api_sei
    --cov-config=.coveragerc
    --ignore=api_sei/__init__.py

markers =
    integration: testes de integracao.
    asyncio: mark a test as an asyncio test.
