[pytest]
addopts =
    -v
    -s
    --cov api_sei
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-report=xml
    --ignore=api_sei/__init__.py

markers =
    integration: testes de integracao.
    asyncio: mark a test as an asyncio test.
