services:
  autodeployer:
    build: 
      context: .
      network: host
      dockerfile: autodeployer.dockerfile
      args:
        GID_DOCKER: ${GID_DOCKER}
        NB_USER: ${NB_USER}
        NB_UID: ${NB_UID}
    user: ${NB_USER}
    tty: true
    stdin_open: true
    restart: on-failure
    env_file: 
      - "./env_files/default.env"
      - "./env_files/security.env"
    volumes:
      - ./known_hosts:/root/.ssh/known_hosts:ro
      - ./env_files/security.env:/app/security.env
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./autodeployer/status/:/app/autodeployer/shared/:rw
      - /opt/sei_similaridade:/opt/sei_similaridade
      - autodeployer-volume:/var/log/autodeployer
    networks:
      - network1
    environment:
      TZ: America/Sao_Paulo

    deploy:
      resources:
        limits:  
          memory: 100mb
          cpus: '1'
volumes:
  autodeployer-volume:
networks:
  network1:
    name: docker-host-bridge
    external: true
