services:
  healthchecker:
    build: 
      context: .
      network: host
      dockerfile: healthchecker.dockerfile
    env_file:
      - env_files/default.env
      - env_files/prod.env
      - env_files/security.env
    environment:
      STORAGE_PROJ_DIR: /opt/sei-ia-storage
      LD_LIBRARY_PATH: /opt/oracle
      ORACLE_HOME: /opt/oracle
      ORACLE_VERSION: 19.25
    command: ["python", "teste.py"]
    networks:
      - network1
    deploy:
      resources:
        limits:
          memory: ${ASSISTENTE_MEM_LIMIT}
          cpus: ${ASSISTENTE_CPU_LIMIT}
    volumes:
      - health_checker_logs:/opt/sei-ia-storage
      - ./:/opt/healthchecker
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true  

volumes:
  health_checker_logs:

networks:
  network1:
    name: docker-host-bridge
    external: true
