[pytest]
env = 
    TEST_SOLR_PORT=8997
    TEST_SOLR_ADDRESS=http://localhost:8997
    TEST_SOLR_PROCESS_CORE_NAME=process
    TEST_SOLR_SEI_PROTOCOLOS_CORE_NAME=sei_protocolos
    TEST_SOLR_PROCESS_CORE_CONF=process
    TEST_SOLR_SEI_PROTOCOLOS_CORE_CONF=sei_protocolos
    TEST_SOLR_IMAGE_NAME=solr:testing
    TEST_SOLR_CONFIGS_SRC_PATH=jobs/configs/solr_core_configs/configsets
    TEST_SOLR_CONFIGS_DST_PATH=tests/integration/solr_core_configs
    TEST_SOLR_DOCKERFILE_SRC_PATH=jobs/configs/solr.dockerfile
    TEST_SOLR_DOCKERFILE_DST_PATH=tests/integration/solr.dockerfile
    TEST_SOLR_SEI_PROTOCOLOS_DATA_PATH=tests/integration/data/solr_external_docs_test_data.json
    TEST_MYSQL_PORT=8998
    TEST_MYSQL_ADDRESS=mysql+pymysql://root:pwd@localhost:8998
    TEST_MYSQL_SEI_DB_NAME=test
    TEST_MYSQL_CONTAINER_NAME=tests-mysql
    TEST_MYSQL_INTERNAL_DOCS_DATA_PATH=tests/integration/data/mysql_internal_docs_test_data.parquet
    TEST_MYSQL_EXTERNAL_DOCS_DATA_PATH=tests/integration/data/mysql_external_docs_test_data.csv
    TEST_MYSQL_SUB_PROCESSES_DATA_PATH=tests/integration/data/subprocesses_test_data.csv
    TEST_MYSQL_RELATED_PROCESSES_DATA_PATH=tests/integration/data/related_processes_docs_test_data.parquet
    TEST_POSTGRES_VERSION_MANAGER_DATA_PATH=tests/integration/data/postgres_version_manager.csv
    TEST_POSTGRES_PORT = 8996
    TEST_POSTGRES_SEI_DB_NAME = sei_similaridade
    TEST_POSTGRES_ADDRESS = postgresql://sei:seisimilaridade@localhost:8996/sei_similaridade
    TEST_POSTGRES_CONTAINER_NAME = tests-postgres
    CONN_STRING_APP_DB=postgresql+psycopg2://sei:seisimilaridade@localhost:8996/sei_similaridade
    MLT_PROCESS_CONFIGSET='/var/solr/configsets/process'
    SOLR_ADDRESS=http://localhost:8997
    SOLR_PORT=8997
    SOLR_MLT_PROCESS_CORE = process

    DB_SEI_USER=root
    DB_SEI_PWD=pwd
    DB_SEI_HOST=localhost
    DB_SEI_DATABASE=test
    DB_SEI_PORT=8998
    DB_SEI_SCHEMA=test
    DATABASE_TYPE=mysql



addopts = 
    -v
    -s 
    --cov jobs
    --cov-config=.coveragerc
    --ignore=jobs/__init__.py

markers =
    integration: testes de integracao.